from setuptools import setup, find_packages

setup(
    name="jules-ai",
    version="70.0.0",
    packages=find_packages(),
    install_requires=[
        "langchain>=0.2.0",
        "langchain-community>=0.2.0",
        "autogen>=0.2.27",
        "pydantic>=2.10.0",
        "pyyaml>=6.0.0",
        "fastapi>=0.115.0",
        "uvicorn>=0.30.0",
        "streamlit>=1.35.0",
        "redis>=5.0.0",
        "sqlalchemy>=2.0.0",
        "chromadb>=0.5.0",
        "prefect>=2.19.0",
        "openai>=1.30.0",
        "transformers>=4.40.0",
        "torch>=2.3.0",
        "numpy>=1.26.0",
        "pandas>=2.2.0",
        "matplotlib>=3.8.0",
        "seaborn>=0.13.0",
        "plotly>=5.20.0",
        "scipy>=1.12.0",
        "scikit-learn>=1.4.0",
        "networkx>=3.2.0",
        "pyro-ppl>=1.9.0",
        "ray>=2.30.0",
        "celery>=5.4.0",
        "web3>=6.0.0",
        "z3-solver>=4.13.0",
        "sympy>=1.12.0",
    ],
    author="Rehan719",
    description="Autonomous scientific enterprise organism with cell signaling, genomic networks, and professional competencies.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/Rehan719/Workstation",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.12",
)
