from .legacy import LawReactor
from .contract import ContractReactor
from .corporate import CorporateLawReactor
from .ip import IPLawReactor
from .litigation import LitigationReactor
from .regulatory import RegulatoryReactor
from .tax import TaxLawReactor
from .employment import EmploymentLawReactor
from .international import InternationalLawReactor
from .family import FamilyLawReactor
from .criminal import CriminalLawReactor
