import os
from typing import Dict, List, Any
from jinja2 import Template
from reportlab.pdfgen import canvas
from docx import Document

class OmnimediaInjector:
    """
    Sovereign Multimodal Output Generation (Truth VIII).
    Generates reports in multiple formats (PDF, DOCX, HTML, etc.).
    """
    def __init__(self, output_dir: str = "outputs/v8_reports"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    async def inject(self, proposal: Dict[str, Any], target_formats: List[str]) -> Dict[str, str]:
        results = {}
        for fmt in target_formats:
            fmt = fmt.lower()
            if fmt == 'pdf':
                results[fmt] = self._generate_pdf(proposal)
            elif fmt == 'docx':
                results[fmt] = self._generate_docx(proposal)
            elif fmt == 'html':
                results[fmt] = self._generate_html(proposal)
            elif fmt in ['pptx', 'xlsx', 'png', 'svg']:
                results[fmt] = self._generate_template_placeholder(proposal, fmt)
            else:
                results[fmt] = self._generate_script_placeholder(proposal, fmt)
        return results

    def _generate_pdf(self, proposal: Dict[str, Any]) -> str:
        filepath = os.path.join(self.output_dir, f"{proposal.get('id', 'report')}.pdf")
        c = canvas.Canvas(filepath)
        c.drawString(100, 750, f"CONSTITUTIONAL PROPOSAL: {proposal.get('title', 'Untitled')}")
        c.drawString(100, 730, f"ID: {proposal.get('id', 'N/A')}")
        c.drawString(100, 710, f"Summary: {proposal.get('executive_summary', '')[:50]}...")
        c.save()
        return filepath

    def _generate_docx(self, proposal: Dict[str, Any]) -> str:
        filepath = os.path.join(self.output_dir, f"{proposal.get('id', 'report')}.docx")
        doc = Document()
        doc.add_heading(f"Constitutional Proposal: {proposal.get('title', 'Untitled')}", 0)
        doc.add_paragraph(f"Executive Summary: {proposal.get('executive_summary', '')}")
        doc.save(filepath)
        return filepath

    def _generate_html(self, proposal: Dict[str, Any]) -> str:
        filepath = os.path.join(self.output_dir, f"{proposal.get('id', 'report')}.html")
        template = Template("""
        <html>
            <head><title>{{ proposal.title }}</title></head>
            <body>
                <h1>Constitutional Proposal: {{ proposal.title }}</h1>
                <p><b>ID:</b> {{ proposal.id }}</p>
                <div>{{ proposal.executive_summary }}</div>
                <hr>
                <small>Generated by Deca-Veritas Omnimedia Injector v8.0</small>
            </body>
        </html>
        """)
        html_content = template.render(proposal=proposal)
        with open(filepath, 'w') as f:
            f.write(html_content)
        return filepath

    def _generate_template_placeholder(self, proposal: Dict[str, Any], fmt: str) -> str:
        filepath = os.path.join(self.output_dir, f"{proposal.get('id', 'report')}.{fmt}")
        with open(filepath, 'w') as f:
            f.write(f"PLACEHOLDER FOR {fmt.upper()} FORMAT\nProposal: {proposal.get('title')}")
        return filepath

    def _generate_script_placeholder(self, proposal: Dict[str, Any], fmt: str) -> str:
        filepath = os.path.join(self.output_dir, f"{proposal.get('id', 'report')}_script.{fmt}")
        with open(filepath, 'w') as f:
            f.write(f"SCRIPT/STUB FOR {fmt.upper()} MULTIMEDIA GENERATION\nProposal: {proposal.get('title')}")
        return filepath
