from .organism.jules_omega_organism_v138 import JulesOmegaOrganismV138
from .orchestration.conscious_organism_v99 import ConsciousOrganismV99_0

# Public Interface Mapping
AI_CEO = JulesOmegaOrganismV138
ConsciousOrganismOrchestrator = ConsciousOrganismV99_0
