"""
Follow-up register — the tasks a round FINDS but does not DO, slotted into the delivery plan and scheduled.

Before this existed a found-but-deferred task lived in a chat chip, a "NOT DONE, and why" paragraph or a
commit message, and nothing made the next round pick it up. Now every such task is a row in
docs/FOLLOWUPS.json with a SLOT — the delivery-plan item whose round will do it (P1.13, P2.6, …),
NEXT (its own round, before the next plan item), or OWNER (it waits on an Owner decision and is never
scheduled into a round). The schedule is DERIVED: the plan's own item order, each open item carrying its
rows. It is rendered between markers into the delivery plan (docs/FABLE_DELIVERY_PROMPT.md) and the
living plan (docs/WORKSTATION_IDBO_LIVING_PLAN.md §6.4), served at GET /api/v1/plan/followups, and
`check()` is enforced by test_w462_followup_register_is_scheduled_and_in_lockstep:

  · an open row on a plan item marked "✅ DONE W###" (right after the item id) fails — the round closed
    without doing or re-slotting it; an item's first line that says done in any other form or place
    ("Done W470", a marker after the [ledger] bracket) fails too, so a mis-typed marker cannot keep rows
    "scheduled" on finished work ("DONE WHEN", the plan's acceptance idiom, is not a marker);
  · owner-gated work is slotted OWNER and nothing else; an unknown slot, a done row with no round, a
    dropped row with no reason and an open row with closed_by fail; a file an open row names must exist in
    the working tree AND be tracked by git (forward slashes, exact case) — the row has gone stale otherwise;
  · a malformed row is REPORTED and skipped, never raised, and never switches the other rules off;
  · each doc carries exactly one marker block, the prompt's inside the real <delivery_plan> section, and
    both equal render() — the docs cannot drift from the register.

CLI: scripts/followups.py (add · list · close · drop · reslot · schedule · render · check).
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Set

# the CLI's tests point this at a scratch copy; nothing else sets it
ROOT = Path(os.environ.get("WORKSTATION_FOLLOWUPS_ROOT") or Path(__file__).resolve().parents[1])
REGISTER = ROOT / "docs" / "FOLLOWUPS.json"
PROMPT = ROOT / "docs" / "FABLE_DELIVERY_PROMPT.md"
LIVING = ROOT / "docs" / "WORKSTATION_IDBO_LIVING_PLAN.md"

BEGIN = "<!-- followups:begin (generated by scripts/followups.py render - never edit by hand) -->"
END = "<!-- followups:end -->"
LOCKSTEP_PROMPT = "the delivery plan's follow-up block is out of lockstep with the register — run render"
LOCKSTEP_LIVING = "the living plan's follow-up block (§6.4) is out of lockstep with the register — run render"
LOCKSTEP = (LOCKSTEP_PROMPT, LOCKSTEP_LIVING)

SEVERITIES = ("high", "medium", "low")
STATUSES = ("open", "done", "dropped")
_SEV_RANK = {s: i for i, s in enumerate(SEVERITIES)}
_ID = re.compile(r"^FU-(\d{3,})$")
_ROUND = re.compile(r"^W\d+$")
_DONE = re.compile(r"^\s*✅ DONE (W\d+)\b")
_DONE_MENTION = re.compile(r"✅|\bdone\b(?!\s+when\b)", re.I)
REQUIRED = ("id", "title", "why", "source", "found", "files", "severity", "owner_gated", "slot", "status")
TEXT_FIELDS = ("id", "title", "why", "source", "found", "slot")


def _reject_constant(name: str) -> Any:
    raise ValueError(f"{name} is not a JSON value")


def parse_register(raw: bytes) -> Any:
    """Strict JSON: NaN / Infinity are refused here, not discovered later when a response cannot serialise."""
    return json.loads(raw.decode("utf-8"), parse_constant=_reject_constant)


def load(path: Optional[Path] = None) -> Dict[str, Any]:
    return parse_register((path or REGISTER).read_bytes())


def save(register: Dict[str, Any], path: Optional[Path] = None) -> None:
    atomic_write(path or REGISTER, (json.dumps(register, indent=2, ensure_ascii=False) + "\n").encode("utf-8"))


REPLACE_TRIES = 50            # × 20 ms: on Windows a reader holding the target makes os.replace fail briefly


def atomic_write(path: Path, data: bytes) -> None:
    """Temp file + os.replace, retried while another process holds the target. The temp never outlives a
    failure or an interrupt, and a failure names the TARGET it could not replace (not the temp)."""
    tmp = path.with_name(path.name + ".tmp")
    try:
        tmp.write_bytes(data)
        for attempt in range(REPLACE_TRIES):
            try:
                os.replace(tmp, path)
                return
            except PermissionError as exc:
                if attempt == REPLACE_TRIES - 1:
                    raise PermissionError(exc.errno, f"{path.name} is held open by another program", str(path)) from exc
                time.sleep(0.02)
    except BaseException:
        try:
            tmp.unlink()
        except OSError:
            pass
        raise


class PartialWrite(OSError):
    """write_all failed AND could not put every already-replaced file back: `unrestored` names them."""

    def __init__(self, cause: BaseException, unrestored: List[Path]):
        super().__init__(f"{cause}; not put back: {', '.join(p.name for p in unrestored)}")
        self.cause = cause
        self.unrestored = unrestored


def write_all(writes: List[Any]) -> None:
    """(path, old_bytes, new_bytes) in order, all or nothing: if a later write fails — or the run is
    interrupted — every file already replaced gets its old bytes back and the error is re-raised. If a
    restore itself fails, PartialWrite names the files still carrying the new bytes (render repairs the docs
    from the register, which is written last). A hard kill between two replaces is the one case this cannot
    cover; check reports it and render repairs it."""
    done: List[Any] = []
    try:
        for path, old, new in writes:
            if new != old:
                atomic_write(path, new)
                done.append((path, old))
    except BaseException as exc:
        unrestored: List[Path] = []
        for path, old in reversed(done):
            try:
                atomic_write(path, old)
            except OSError:
                unrestored.append(path)
        if unrestored:
            raise PartialWrite(exc, unrestored) from exc
        raise


def read_doc(path: Path) -> str:
    """Docs are read as bytes so a doc's own line endings survive a round trip (read_text would fold CRLF)."""
    return path.read_bytes().decode("utf-8")


def delivery_plan_body(prompt_text: str) -> Optional[str]:
    """The real <delivery_plan> section — the tag on a line of its own, not a prose mention of it."""
    m = re.search(r"^<delivery_plan>[ \t]*\r?$(.*?)^</delivery_plan>[ \t]*\r?$", prompt_text, flags=re.M | re.S)
    return m.group(1) if m else None


def _without_blocks(text: str) -> str:
    return re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), "", text, flags=re.S)


def plan_items(prompt_text: str) -> List[Dict[str, Any]]:
    """The delivery plan's items IN PLAN ORDER, each with its done state — read from the plan itself,
    so a newly added item or a new "✅ DONE W###" marker is seen without touching this module."""
    body = delivery_plan_body(prompt_text)
    if body is None:
        return []
    items = []
    for line in _without_blocks(body).splitlines():
        m = re.match(r"^ (P\d+\.\d+)\b(.*?)\r?$", line)
        if not m:
            continue
        rest = m.group(2).replace("️", "")           # a variation selector must not hide a marker
        done = _DONE.match(rest)                           # only right after the id — never a cross-reference
        title = _DONE.sub("", rest) if done else rest
        title = re.sub(r"^\s*\[[^\]]*\]\s*", "", title).strip()
        title = title.split(". ")[0].rstrip(".")          # the item's name: its first sentence
        items.append({"slot": m.group(1), "title": title[:110], "done": bool(done),
                      "done_by": done.group(1) if done else None,
                      # said done in any other form or place on the line: reported, never read as open
                      "malformed_done": (not done) and bool(_DONE_MENTION.search(rest))})
    return items


def _row_shape_problems(r: Any, idx: int) -> List[str]:
    if not isinstance(r, dict):
        return [f"row {idx}: not an object"]
    rid = r.get("id") if isinstance(r.get("id"), str) else f"row {idx}"
    missing = [k for k in REQUIRED if k not in r]
    if missing:
        return [f"{rid}: missing {', '.join(missing)}"]
    p: List[str] = []
    for k in TEXT_FIELDS:
        v = r[k]
        if not isinstance(v, str) or not v.strip():
            p.append(f"{rid}: {k} must be a non-empty string")
        elif "\r" in v or "\n" in v or BEGIN in v or END in v:
            p.append(f"{rid}: {k} must be one line (no line breaks or markers)")
    if not isinstance(r["owner_gated"], bool):
        p.append(f"{rid}: owner_gated must be true or false (not {r['owner_gated']!r})")
    if not isinstance(r["files"], list) or not all(isinstance(f, str) and f.strip() for f in r["files"]):
        p.append(f"{rid}: files must be a list of repository paths")
    if r["severity"] not in SEVERITIES:
        p.append(f"{rid}: severity must be one of {SEVERITIES}")
    if r["status"] not in STATUSES:
        p.append(f"{rid}: status must be one of {STATUSES}")
    for k in ("closed_by", "note"):
        if k in r and r[k] is not None and not isinstance(r[k], str):
            p.append(f"{rid}: {k} must be a string or null")
    return p


def raw_items(register: Any) -> List[Any]:
    items = register.get("items") if isinstance(register, dict) else None
    return items if isinstance(items, list) else []


def _rows(register: Any) -> List[Dict[str, Any]]:
    """The well-formed rows only — everything that renders or schedules reads these, so a malformed row is
    reported by check() and can never crash a renderer or reach a page as an object."""
    return [r for i, r in enumerate(raw_items(register)) if not _row_shape_problems(r, i)]


def id_number(value: Any) -> Optional[int]:
    """Lenient: 'FU-14', 'fu-014 ' and 'FU-014' are all 14 — used for numbering and duplicate detection."""
    m = re.search(r"(\d+)", str(value))
    return int(m.group(1)) if m else None


def _num(r: Dict[str, Any]) -> int:
    m = _ID.match(str(r.get("id", "")))
    return int(m.group(1)) if m else 10 ** 9


def _ordered(rows: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    # severity first, then the order they were found (the register is append-only; ids compared as numbers)
    return sorted(rows, key=lambda r: (_SEV_RANK.get(str(r.get("severity")), 9), _num(r)))


def schedule(register: Dict[str, Any], prompt_text: str) -> Dict[str, Any]:
    items = plan_items(prompt_text)
    rows = _rows(register)
    open_rows = [r for r in rows if r["status"] == "open"]
    riders = [r for r in open_rows if r["owner_gated"] is not True]
    first_open = next((i["slot"] for i in items if not i["done"]), None)
    slots: List[Dict[str, Any]] = []
    nxt = _ordered([r for r in riders if r["slot"] == "NEXT"])
    if nxt:
        slots.append({"slot": "NEXT", "title": f"its own round, before {first_open or 'the next plan item'}",
                      "items": nxt})
    seen: Set[str] = set()
    for it in items:
        if it["done"] or it["slot"] in seen:
            continue
        seen.add(it["slot"])
        slotted = _ordered([r for r in riders if r["slot"] == it["slot"]])
        if slotted:
            slots.append({"slot": it["slot"], "title": it["title"], "items": slotted})
    closed = [r for r in rows if r["status"] != "open"]
    return {
        "counts": {
            "open": len(open_rows),
            "scheduled": sum(len(s["items"]) for s in slots),
            "high": sum(1 for r in riders if r["severity"] == "high"),
            "awaiting_owner": sum(1 for r in open_rows if r["owner_gated"] is True),
            "done": sum(1 for r in closed if r["status"] == "done"),
            "dropped": sum(1 for r in closed if r["status"] == "dropped"),
        },
        "next_plan_item": first_open,
        "schedule": slots,
        "awaiting_owner": _ordered([r for r in open_rows if r["owner_gated"] is True]),
        "closed": closed,
    }


# indented two spaces so no rendered line can ever match the plan's " P1.12 …" item lines
def _row_line(r: Dict[str, Any]) -> str:
    return f"    {r['id']} [{r['severity']}] {r['title']} — {r['why']} (found {r['source']})"


def render(register: Dict[str, Any], prompt_text: str) -> str:
    """The block both docs carry between the markers (plain text, LF; splice converts per doc)."""
    s = schedule(register, prompt_text)
    c = s["counts"]
    out = [
        "SCHEDULED FOLLOW-UPS — every task a round finds and does not do is a row in docs/FOLLOWUPS.json,",
        "added in the same commit (python scripts/followups.py add), slotted to the plan item whose round does",
        "it, NEXT (its own round), or OWNER (waits on an Owner decision; never scheduled). A round that marks a",
        "plan item \"✅ DONE W###\" closes or re-slots that item's rows first — the suite fails otherwise.",
        f"Open {c['open']} ({c['scheduled']} scheduled, {c['high']} high · {c['awaiting_owner']} awaiting the Owner)"
        f" · done {c['done']} · dropped {c['dropped']}.",
    ]
    if not s["schedule"]:
        out.append("  (nothing scheduled)")
    for slot in s["schedule"]:
        out.append(f"  {slot['slot']} — {slot['title']}")
        out.extend(_row_line(r) for r in slot["items"])
    if s["awaiting_owner"]:
        out.append("  AWAITING THE OWNER — recorded, never scheduled into a round without the Owner's instruction:")
        out.extend(_row_line(r) for r in s["awaiting_owner"])
    return "\n".join(out)


def _marker_problem(text: str, name: str) -> Optional[str]:
    b, e = text.count(BEGIN), text.count(END)
    if b != 1 or e != 1 or text.index(BEGIN) > text.index(END):
        return f"{name} must carry exactly one follow-up marker pair (found {b} begin, {e} end)"
    return None


def _block(text: str) -> Optional[str]:
    if _marker_problem(text, "doc"):
        return None
    return text.split(BEGIN, 1)[1].split(END, 1)[0].replace("\r\n", "\n").strip("\n")


def splice(text: str, block: str) -> str:
    """Replace the marker block in a doc, preserving that doc's line endings. Refuses a doc whose markers
    are missing or duplicated — a second, stale copy would never be compared or re-rendered."""
    bad = _marker_problem(text, "the doc")
    if bad:
        raise ValueError(bad)
    crlf = "\r\n" in text
    new = "\n" + block + "\n"
    if crlf:
        new = new.replace("\n", "\r\n")
    head, tail = text.split(BEGIN, 1)
    return head + BEGIN + new + END + tail.split(END, 1)[1]


def normalise_path(f: str) -> str:
    f = f.strip().replace("\\", "/")
    while f.startswith("./"):
        f = f[2:]
    return f


def _tracked(root: Path) -> Optional[Set[str]]:
    try:
        out = subprocess.run(["git", "ls-files", "-z"], cwd=str(root), capture_output=True, timeout=20)
        if out.returncode == 0:
            return {p for p in out.stdout.decode("utf-8", "replace").split("\0") if p}
    except (OSError, subprocess.SubprocessError):
        pass
    return None


def _exists_exact(root: Path, rel: str) -> bool:
    # each component with its exact case (Windows would otherwise accept any case), and a FILE at the end
    cur = root
    for part in rel.split("/"):
        try:
            if part not in {p.name for p in cur.iterdir()}:
                return False
        except OSError:
            return False
        cur = cur / part
    return cur.is_file()


def check(register: Any, prompt_text: str, living_text: Optional[str] = None,
          root: Optional[Path] = None) -> List[str]:
    """Every problem with the register and its two rendered copies, as sentences. Never raises on a
    malformed register — a problem is reported, not hidden behind a traceback."""
    root = root or ROOT
    problems: List[str] = []
    body = delivery_plan_body(prompt_text)
    items = plan_items(prompt_text)
    if body is None or not items:
        return ["the delivery plan has no <delivery_plan> section with items to slot follow-ups into"]
    for it in items:
        if it["malformed_done"]:
            problems.append(f"plan item {it['slot']} says done, but not as '✅ DONE W###' right after its id — "
                            "the register cannot tell whether it is done")
    counts: Dict[str, int] = {}
    for it in items:
        counts[it["slot"]] = counts.get(it["slot"], 0) + 1
    problems += [f"plan item {s} appears {n} times in the delivery plan" for s, n in counts.items() if n > 1]
    by_slot = {i["slot"]: i for i in items}

    if not isinstance(register, dict) or not isinstance(register.get("items"), list):
        return problems + ["the register must be an object with an items list"]
    raw = register["items"]
    for i, r in enumerate(raw):
        problems += _row_shape_problems(r, i)         # reported; the row is skipped below, the rules still run
    rows = _rows(register)

    numbers: Dict[int, List[str]] = {}
    for r in raw:
        if isinstance(r, dict) and id_number(r.get("id")) is not None:
            numbers.setdefault(id_number(r.get("id")), []).append(str(r.get("id")))
    problems += [f"{ids[0]}: duplicate id ({', '.join(repr(x) for x in ids)})" for ids in numbers.values() if len(ids) > 1]

    tracked = _tracked(root) if any(r["status"] == "open" and r["files"] for r in rows) else None
    for r in rows:
        rid = r["id"]
        if not _ID.match(rid):
            problems.append(f"{rid}: id must look like FU-001")
        slot = r["slot"]
        if r["status"] == "done":
            if not _ROUND.match(r.get("closed_by") or ""):
                problems.append(f"{rid}: done without closed_by naming the round (W###)")
            continue
        if r["status"] == "dropped":
            if not (r.get("note") or "").strip():
                problems.append(f"{rid}: dropped without a note saying why")
            continue
        # open
        if r.get("closed_by"):
            problems.append(f"{rid}: open but closed_by is set ({r['closed_by']}) — close it or clear closed_by")
        if r["owner_gated"]:
            if slot != "OWNER":
                problems.append(f"{rid}: owner-gated work is slotted OWNER, never {slot} — it is not scheduled into a round")
        elif slot == "OWNER":
            problems.append(f"{rid}: slot OWNER but owner_gated is false")
        elif slot == "NEXT":
            pass
        elif slot not in by_slot:
            problems.append(f"{rid}: slot {slot} is not a delivery-plan item (nor NEXT / OWNER)")
        elif by_slot[slot]["done"]:
            problems.append(f"{rid}: rides on {slot}, already DONE {by_slot[slot]['done_by']} — "
                            f"that round closed without doing it: close it, drop it with a reason, or re-slot it")
        for f in r["files"]:
            if f != normalise_path(f) or f.startswith("/") or re.match(r"^[A-Za-z]:", f):
                problems.append(f"{rid}: names {f!r} — use a repository-relative path with forward slashes")
            elif not _exists_exact(root, f):
                problems.append(f"{rid}: names {f}, which is not in the working tree — the row has gone stale")
            elif tracked is not None and f not in tracked:
                problems.append(f"{rid}: names {f}, which git does not track yet — git add it (CI only sees tracked files)")

    for text, name, lockstep in ((prompt_text, "the delivery plan", LOCKSTEP_PROMPT),
                                 (living_text, "the living plan", LOCKSTEP_LIVING)):
        if text is None:
            continue
        bad = _marker_problem(text, name)
        if bad:
            problems.append(bad)
            continue
        if _block(text) != render(register, prompt_text):
            problems.append(lockstep)
    if BEGIN in prompt_text and BEGIN not in body:
        problems.append("the delivery plan's follow-up block must sit inside the <delivery_plan> section")
    return problems
