"""
Follow-up register — the tasks a round FINDS but does not DO, slotted into the delivery plan and scheduled.

Before this existed a found-but-deferred task lived in a chat chip, a "NOT DONE, and why" paragraph or a
commit message, and nothing made the next round pick it up. Now every such task is a row in
docs/FOLLOWUPS.json with a SLOT — the delivery-plan item whose round will do it (P1.13, P2.6, …), or OWNER
(it waits on an Owner decision and is never scheduled into a round). The schedule is DERIVED: the plan's own
item order, each open item carrying its rows. It is rendered between markers into the delivery plan
(docs/FABLE_DELIVERY_PROMPT.md) and the living plan (docs/WORKSTATION_IDBO_LIVING_PLAN.md §6.4), served at
GET /api/v1/plan/followups, and `check()` is enforced by test_w462_followup_register_is_scheduled_and_in_lockstep
and test_w469_the_plan_carries_every_followup_and_keeps_itself_current.

W469 (the Owner's instruction, 2026-09-17) — the plan keeps itself current:
  · NEXT is retired. It meant "its own round, before the next plan item", and because rounds register more
    than they close, the NEXT queue grew (25 → 42 rows) and held P1.13 back indefinitely. Every row now rides
    the plan item that owns its area, so found work lengthens that item instead of queueing in front of the plan.
  · ROUTES (register["routes"], in precedence order) name the item that owns an area — by file prefix or by a
    word in the row's title. `followups.py add` routes a row with no --slot; a HIGH row rides the next open
    item. A route pointing at a DONE item fails the check, so a finished item hands its area on.
  · PLAN NOW — a second generated block (next item, the order after it with each item's riders, done per
    phase, follow-up totals) replaces the hand-kept "NEXT —" line in WHERE THE PLAN STANDS and sits in the
    living plan's §6.4; `followups.py done P1.13 --by W470` marks an item done, moves its riders along the
    routes, and re-renders both docs in one locked write.

What check() enforces:
  · an open row slotted NEXT fails (retired, W469); a route that is malformed, names no plan item or points at a
    finished item fails;
  · an open row on a plan item marked "✅ DONE W###" (right after the item id) fails — the round closed
    without doing or re-slotting it; an item's first line that says done in any other form or place
    ("Done W470", a marker after the [ledger] bracket) fails too, so a mis-typed marker cannot keep rows
    "scheduled" on finished work ("DONE WHEN", the plan's acceptance idiom, is not a marker);
  · owner-gated work is slotted OWNER and nothing else; an unknown slot, a done row with no round, a
    dropped row with no reason and an open row with closed_by fail; a file an open row names must exist in
    the working tree AND be tracked by git (forward slashes, exact case) — the row has gone stale otherwise;
  · a malformed row is REPORTED and skipped, never raised, and never switches the other rules off;
  · each doc carries exactly one follow-up block and one PLAN NOW block, the prompt's inside the real
    <delivery_plan> section, and each equals its render — the docs cannot drift from the plan or the register.

CLI: scripts/followups.py (add · list · close · drop · reslot · route · routes · done · schedule · render · check).
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Set

# the CLI's tests point this at a scratch copy; nothing else sets it
ROOT = Path(os.environ.get("WORKSTATION_FOLLOWUPS_ROOT") or Path(__file__).resolve().parents[1])
REGISTER = ROOT / "docs" / "FOLLOWUPS.json"
PROMPT = ROOT / "docs" / "FABLE_DELIVERY_PROMPT.md"
LIVING = ROOT / "docs" / "WORKSTATION_IDBO_LIVING_PLAN.md"

BEGIN = "<!-- followups:begin (generated by scripts/followups.py render - never edit by hand) -->"
END = "<!-- followups:end -->"
LOCKSTEP_PROMPT = "the delivery plan's follow-up block is out of lockstep with the register — run render"
LOCKSTEP_LIVING = "the living plan's follow-up block (§6.4) is out of lockstep with the register — run render"
# W469 — the PLAN NOW block: generated from the plan's items and the register, never kept by hand
PLAN_BEGIN = "<!-- plannow:begin (generated by scripts/followups.py render - never edit by hand) -->"
PLAN_END = "<!-- plannow:end -->"
LOCKSTEP_PLAN_PROMPT = "the delivery plan's PLAN NOW block is out of lockstep with the plan and the register — run render"
LOCKSTEP_PLAN_LIVING = "the living plan's PLAN NOW block (§6.4) is out of lockstep with the plan and the register — run render"
# W486 — the PACE block: what the plan's own record says about how fast it is moving, generated the
# same way and held to the same lockstep, so it can never drift into a claim nobody re-derived.
PACE_BEGIN = "<!-- pace:begin (generated by scripts/followups.py render - never edit by hand) -->"
PACE_END = "<!-- pace:end -->"
LOCKSTEP_PACE_PROMPT = "the delivery plan's PACE block is out of lockstep with the plan and the register — run render"
LOCKSTEP_PACE_LIVING = "the living plan's PACE block (§6.4) is out of lockstep with the plan and the register — run render"
LOCKSTEP = (LOCKSTEP_PROMPT, LOCKSTEP_LIVING, LOCKSTEP_PLAN_PROMPT, LOCKSTEP_PLAN_LIVING,
            LOCKSTEP_PACE_PROMPT, LOCKSTEP_PACE_LIVING)
RETIRED_SLOTS = ("NEXT",)
_ITEM_SLOT = re.compile(r"^P\d+\.\d+$")

SEVERITIES = ("high", "medium", "low")
STATUSES = ("open", "done", "dropped")
_SEV_RANK = {s: i for i, s in enumerate(SEVERITIES)}
_ID = re.compile(r"^FU-(\d{3,})$")
_ROUND = re.compile(r"^W\d+$")
_DONE = re.compile(r"^\s*✅ DONE (W\d+)\b")
# W473 (FU-069) — a done marker in another form is read only where the marker belongs: right after the id (a check
# mark anywhere still counts, since nothing else on an item line uses one); the word 'done' inside the prose of an
# item ('counted as done only when verified') is prose
_DONE_MENTION = re.compile(r"^\s*[\[(\-–—\s]*(?:✅|\bdone\b(?!\s+when\b))|✅|\bDONE\s+W\d+\b", re.I)
REQUIRED = ("id", "title", "why", "source", "found", "files", "severity", "owner_gated", "slot", "status")
TEXT_FIELDS = ("id", "title", "why", "source", "found", "slot")


def _reject_constant(name: str) -> Any:
    raise ValueError(f"{name} is not a JSON value")


def parse_register(raw: bytes) -> Any:
    """Strict JSON: NaN / Infinity are refused here, not discovered later when a response cannot serialise."""
    return json.loads(raw.decode("utf-8"), parse_constant=_reject_constant)


def load(path: Optional[Path] = None) -> Dict[str, Any]:
    return parse_register((path or REGISTER).read_bytes())


def save(register: Dict[str, Any], path: Optional[Path] = None) -> None:
    atomic_write(path or REGISTER, (json.dumps(register, indent=2, ensure_ascii=False) + "\n").encode("utf-8"))


REPLACE_TRIES = 50            # × 20 ms: on Windows a reader holding the target makes os.replace fail briefly


def atomic_write(path: Path, data: bytes) -> None:
    """Temp file + os.replace, retried while another process holds the target. The temp never outlives a
    failure or an interrupt, and a failure names the TARGET it could not replace (not the temp)."""
    tmp = path.with_name(path.name + ".tmp")
    try:
        tmp.write_bytes(data)
        for attempt in range(REPLACE_TRIES):
            try:
                os.replace(tmp, path)
                return
            except PermissionError as exc:
                if attempt == REPLACE_TRIES - 1:
                    raise PermissionError(exc.errno, f"{path.name} is held open by another program", str(path)) from exc
                time.sleep(0.02)
    except BaseException:
        try:
            tmp.unlink()
        except OSError:
            pass
        raise


class PartialWrite(OSError):
    """write_all failed AND could not put every already-replaced file back: `unrestored` names them."""

    def __init__(self, cause: BaseException, unrestored: List[Path]):
        super().__init__(f"{cause}; not put back: {', '.join(p.name for p in unrestored)}")
        self.cause = cause
        self.unrestored = unrestored


def write_all(writes: List[Any]) -> None:
    """(path, old_bytes, new_bytes) in order, all or nothing: if a later write fails — or the run is
    interrupted — every file already replaced gets its old bytes back and the error is re-raised. If a
    restore itself fails, PartialWrite names the files still carrying the new bytes (render repairs the docs
    from the register, which is written last). A hard kill between two replaces is the one case this cannot
    cover; check reports it and render repairs it."""
    done: List[Any] = []
    try:
        for path, old, new in writes:
            if new != old:
                atomic_write(path, new)
                done.append((path, old))
    except BaseException as exc:
        unrestored: List[Path] = []
        for path, old in reversed(done):
            try:
                atomic_write(path, old)
            except OSError:
                unrestored.append(path)
        if unrestored:
            raise PartialWrite(exc, unrestored) from exc
        raise


def read_doc(path: Path) -> str:
    """Docs are read as bytes so a doc's own line endings survive a round trip (read_text would fold CRLF)."""
    return path.read_bytes().decode("utf-8")


def delivery_plan_body(prompt_text: str) -> Optional[str]:
    """The real <delivery_plan> section — the tag on a line of its own, not a prose mention of it."""
    m = re.search(r"^<delivery_plan>[ \t]*\r?$(.*?)^</delivery_plan>[ \t]*\r?$", prompt_text, flags=re.M | re.S)
    return m.group(1) if m else None


def _without_blocks(text: str) -> str:
    text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), "", text, flags=re.S)
    return re.sub(re.escape(PLAN_BEGIN) + r".*?" + re.escape(PLAN_END), "", text, flags=re.S)


def _item_blocks(body: str) -> Dict[str, str]:
    """Each delivery-plan item's whole text (its id line and the indented lines under it), keyed by slot."""
    blocks: Dict[str, str] = {}
    cur = None
    for line in _without_blocks(body).splitlines():
        m = re.match(r"^ (P\d+\.\d+)\b", line)
        if m:
            cur = m.group(1)
            blocks[cur] = line
        elif cur and (line.startswith("      ") or not line.strip()):
            blocks[cur] += "\n" + line
        else:
            cur = None
    return blocks


def plan_items(prompt_text: str) -> List[Dict[str, Any]]:
    """The delivery plan's items IN PLAN ORDER, each with its done state — read from the plan itself,
    so a newly added item or a new "✅ DONE W###" marker is seen without touching this module."""
    body = delivery_plan_body(prompt_text)
    if body is None:
        return []
    items = []
    for line in _without_blocks(body).splitlines():
        m = re.match(r"^ (P\d+\.\d+)\b(.*?)\r?$", line)
        if not m:
            continue
        rest = m.group(2).replace("️", "")           # a variation selector must not hide a marker
        done = _DONE.match(rest)                           # only right after the id — never a cross-reference
        title = _DONE.sub("", rest) if done else rest
        title = re.sub(r"^\s*\[[^\]]*\]\s*", "", title).strip()
        title = title.split(". ")[0].rstrip(".")          # the item's name: its first sentence
        items.append({"slot": m.group(1), "title": title[:110], "done": bool(done),
                      "done_by": done.group(1) if done else None,
                      # said done in any other form or place on the line: reported, never read as open
                      "malformed_done": (not done) and bool(_DONE_MENTION.search(rest))})
    return items


def _row_shape_problems(r: Any, idx: int) -> List[str]:
    if not isinstance(r, dict):
        return [f"row {idx}: not an object"]
    rid = r.get("id") if isinstance(r.get("id"), str) else f"row {idx}"
    missing = [k for k in REQUIRED if k not in r]
    if missing:
        return [f"{rid}: missing {', '.join(missing)}"]
    p: List[str] = []
    for k in TEXT_FIELDS:
        v = r[k]
        if not isinstance(v, str) or not v.strip():
            p.append(f"{rid}: {k} must be a non-empty string")
        elif "\r" in v or "\n" in v or any(m in v for m in (BEGIN, END, PLAN_BEGIN, PLAN_END)):
            p.append(f"{rid}: {k} must be one line (no line breaks or markers)")
    if not isinstance(r["owner_gated"], bool):
        p.append(f"{rid}: owner_gated must be true or false (not {r['owner_gated']!r})")
    if not isinstance(r["files"], list) or not all(isinstance(f, str) and f.strip() for f in r["files"]):
        p.append(f"{rid}: files must be a list of repository paths")
    if r["severity"] not in SEVERITIES:
        p.append(f"{rid}: severity must be one of {SEVERITIES}")
    if r["status"] not in STATUSES:
        p.append(f"{rid}: status must be one of {STATUSES}")
    for k in ("closed_by", "note"):
        if k in r and r[k] is not None and not isinstance(r[k], str):
            p.append(f"{rid}: {k} must be a string or null")
    return p


def raw_items(register: Any) -> List[Any]:
    items = register.get("items") if isinstance(register, dict) else None
    return items if isinstance(items, list) else []


def _rows(register: Any) -> List[Dict[str, Any]]:
    """The well-formed rows only — everything that renders or schedules reads these, so a malformed row is
    reported by check() and can never crash a renderer or reach a page as an object."""
    return [r for i, r in enumerate(raw_items(register)) if not _row_shape_problems(r, i)]


def id_number(value: Any) -> Optional[int]:
    """Lenient: 'FU-14', 'fu-014 ' and 'FU-014' are all 14 — used for numbering and duplicate detection."""
    m = re.search(r"(\d+)", str(value))
    return int(m.group(1)) if m else None


def _num(r: Dict[str, Any]) -> int:
    m = _ID.match(str(r.get("id", "")))
    return int(m.group(1)) if m else 10 ** 9


def _ordered(rows: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    # severity first, then the order they were found (the register is append-only; ids compared as numbers)
    return sorted(rows, key=lambda r: (_SEV_RANK.get(str(r.get("severity")), 9), _num(r)))


def _open_items(items: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    seen: Set[str] = set()
    out = []
    for it in items:
        if it["done"] or it["slot"] in seen:
            continue
        seen.add(it["slot"])
        out.append(it)
    return out


def _gate_phase(open_items: List[Dict[str, Any]]) -> Optional[str]:
    return open_items[0]["slot"].split(".")[0] if open_items else None


def _prioritised(rows: List[Dict[str, Any]], cfg: Dict[str, Any], gate: Optional[str]) -> List[Dict[str, Any]]:
    """W478 — each row a COPY carrying its priority (score, parts, basis); highest first, the old order breaking ties."""
    from agentic_core import plan_priority as pp
    out = [dict(r, priority=pp.score_row(r, cfg, gate)) for r in rows]
    return sorted(out, key=lambda r: (-r["priority"]["score"], _SEV_RANK.get(str(r.get("severity")), 9), _num(r)))


def schedule(register: Dict[str, Any], prompt_text: str) -> Dict[str, Any]:
    from agentic_core import plan_priority as pp
    items = plan_items(prompt_text)
    rows = _rows(register)
    open_rows = [r for r in rows if r["status"] == "open"]
    riders = [r for r in open_rows if r["owner_gated"] is not True]
    open_items = _open_items(items)
    first_open = open_items[0]["slot"] if open_items else None
    cfg, cfg_problems = pp.load_config(ROOT)
    gate = _gate_phase(open_items)
    slots: List[Dict[str, Any]] = []
    for it in open_items:
        # W478 — inside an item the rows run highest-priority first (the plan's item order and phase gates stand)
        slotted = _prioritised([r for r in riders if r["slot"] == it["slot"]], cfg, gate)
        if slotted:
            slots.append({"slot": it["slot"], "title": it["title"], "items": slotted,
                          "open_priority": round(sum(r["priority"]["score"] for r in slotted), 1)})
    # W469 — a row that rides no open plan item (the retired NEXT, an unknown slot, a finished item) is shown, never
    # silently left out of the schedule; check() names what to do with it
    open_slots = {it["slot"] for it in open_items}
    # a plan with no readable items classifies nothing: every row is not 'unscheduled' because the plan is unreadable
    unscheduled = _ordered([r for r in riders if r["slot"] not in open_slots]) if items else []
    closed = [r for r in rows if r["status"] != "open"]
    return {
        "counts": {
            "open": len(open_rows),
            "scheduled": sum(len(s["items"]) for s in slots),
            "unscheduled": len(unscheduled),
            "high": sum(1 for s_ in slots for r in s_["items"] if r["severity"] == "high"),
            "awaiting_owner": sum(1 for r in open_rows if r["owner_gated"] is True),
            "done": sum(1 for r in closed if r["status"] == "done"),
            "dropped": sum(1 for r in closed if r["status"] == "dropped"),
        },
        "next_plan_item": first_open,
        "schedule": slots,
        "unscheduled": unscheduled,
        "awaiting_owner": _ordered([r for r in open_rows if r["owner_gated"] is True]),
        "closed": closed,
        # W478 — the priority in force: completion weighted by what the rows are worth, and the open items by total
        # open priority for the Owner to consider beside the plan's own order (never applied automatically)
        "priority": {
            "gate_phase": gate,
            "config": "docs/PRIORITY.json" if pp.config_path(ROOT).exists() else "built-in defaults (no docs/PRIORITY.json)",
            "config_problems": cfg_problems,
            "completion": pp.completion(rows, cfg, gate),
            "suggested_order": [s_["slot"] for s_ in sorted(slots, key=lambda s_: -s_["open_priority"])],
        },
    }


# ── W469 — routes: which plan item owns an area, so a found task rides the plan instead of queueing before it ──
def raw_routes(register: Any) -> List[Any]:
    routes = register.get("routes") if isinstance(register, dict) else None
    return routes if isinstance(routes, list) else []


def _route_shape_problems(rt: Any, idx: int) -> List[str]:
    name = f"route {idx + 1}"
    if not isinstance(rt, dict):
        return [f"{name}: not an object"]
    p: List[str] = []
    slot = rt.get("slot")
    if not isinstance(slot, str) or not _ITEM_SLOT.match(slot):
        p.append(f"{name}: slot must name a delivery-plan item like P2.9 (not {slot!r})")
    for key in ("files", "words"):
        v = rt.get(key, [])
        if not isinstance(v, list) or not all(isinstance(x, str) and x.strip() for x in v):
            p.append(f"{name}: {key} must be a list of non-empty strings")
    if not p:
        if not rt.get("files") and not rt.get("words"):
            p.append(f"{name} ({slot}): needs at least one file prefix or title word to match")
        bad = [f for f in rt.get("files", []) if f != normalise_path(f) or f.startswith("/") or re.match(r"^[A-Za-z]:", f)]
        if bad:
            p.append(f"{name} ({slot}): file prefix {bad[0]!r} must be repository-relative with forward slashes")
        if any(w != w.strip().lower() for w in rt.get("words", [])):
            p.append(f"{name} ({slot}): title words are matched in lower case — write them in lower case")
    if "note" in rt and not isinstance(rt["note"], str):
        p.append(f"{name}: note must be a string")
    if "handed_from" in rt:
        hf = rt["handed_from"]
        if not (isinstance(hf, str) and _ITEM_SLOT.match(hf)):
            p.append(f"{name} ({slot}): handed_from must name a plan item (P#.#)")
        elif hf == slot:
            p.append(f"{name} ({slot}): handed_from names the route's own item")
    return p


def merge_routes(register: Dict[str, Any], from_slot: str, to_slot: str) -> int:
    """W469 (refutation) — hand an item's area to another. W473 (register FU-073): the handed route KEEPS ITS PLACE
    and only its slot changes — it becomes a second route to `to_slot` marked `handed_from`, so the handed area keeps
    exactly the precedence it had and the taker's own matchers stay where they were (the W469 merge moved the taker's
    broad prefixes to the handed route's position: done P1.13 --hand-to P1.16 lifted docs/ and integration_tests/ to
    the first route). (Refutation) EVERY moving route is handed in its own place — nothing is ever joined; a route
    handed on again keeps `handed_from` = the item it first belonged to and its note says `via`. A malformed route is
    never merged (its string would be read letter by letter), and a route that was itself handed from `to_slot` is
    never handed back to it (it would name its own item): ValueError, repair it first. Returns how many routes were
    handed (0: nothing to hand)."""
    routes = register.setdefault("routes", [])
    if not isinstance(routes, list):
        raise ValueError("the register's routes are not a list — repair it by hand first")
    moving = [rt for rt in routes if isinstance(rt, dict) and rt.get("slot") == from_slot]
    handed = len(moving)
    if not moving:
        return 0
    for rt in moving:
        shape = _route_shape_problems(rt, routes.index(rt))
        if shape:
            raise ValueError(f"{shape[0]} — repair that route before handing its area on")
        if rt.get("handed_from") == to_slot:
            raise ValueError(f"the route to {from_slot} was handed from {to_slot}; it cannot go back to it — remove it "
                             f"(python scripts/followups.py route --slot {from_slot} --remove --handed) or hand it elsewhere")
    for rt in moving:                                  # (refutation) each route keeps its own place and its origin
        rt["slot"] = to_slot
        origin = rt.get("handed_from") or from_slot    # a route handed on again keeps the item it first belonged to
        rt["handed_from"] = origin
        rt["note"] = "; ".join(dict.fromkeys(n for n in (f"handed from {origin} via {from_slot}" if origin != from_slot
                                                        else f"handed from {from_slot}", rt.get("note")) if n))
    return handed


def _routes(register: Any) -> List[Dict[str, Any]]:
    return [rt for i, rt in enumerate(raw_routes(register)) if not _route_shape_problems(rt, i)]


def _route_matches(rt: Dict[str, Any], title: str, files: List[str]) -> Optional[str]:
    """How the route matches a row — a file under one of its prefixes, or one of its words in the row's title (whole
    words, lower case) — or None."""
    for f in files:
        for prefix in rt.get("files", []):
            if f == prefix or (prefix.endswith("/") and f.startswith(prefix)):
                return f"file {f} (route {rt['slot']}: {prefix})"
    low = title.lower()
    for w in rt.get("words", []):
        if re.search(r"(?<![a-z0-9_])" + re.escape(w) + r"(?![a-z0-9_])", low):
            return f"title word '{w}' (route {rt['slot']})"
    return None


def route_row(register: Any, prompt_text: str, title: str, files: List[str], severity: str,
              exclude: Optional[Set[str]] = None) -> Dict[str, Any]:
    """The plan item a new or moved row rides: a HIGH row rides the next open item (it must not wait for its area's
    turn); otherwise the first route (in the register's order) that matches and points at an open item. A route
    pointing at a finished item is skipped here (check() reports it). {slot: None, reason} when nothing matches."""
    exclude = exclude or set()
    open_items = [it for it in _open_items(plan_items(prompt_text)) if it["slot"] not in exclude]
    open_slots = {it["slot"] for it in open_items}
    if severity == "high":
        if open_items:
            return {"slot": open_items[0]["slot"], "by": "high severity rides the next open plan item"}
        return {"slot": None, "reason": "a high-severity row rides the next open plan item, and none is open"}
    for rt in _routes(register):
        if rt["slot"] not in open_slots:
            continue
        how = _route_matches(rt, title, [normalise_path(f) for f in files])
        if how:
            return {"slot": rt["slot"], "by": how}
    return {"slot": None,
            "reason": "no route matches its files or title — name the plan item with --slot (or add a route: "
                      "python scripts/followups.py route --slot P… --files … --words …)"}


# ── W469 — PLAN NOW: the plan's live state, generated, so no hand-kept line can go stale ──
def plan_now(register: Any, prompt_text: str) -> Dict[str, Any]:
    items = plan_items(prompt_text)
    s = schedule(register if isinstance(register, dict) else {"items": []}, prompt_text)
    riding = {x["slot"]: x["items"] for x in s["schedule"]}
    phases: List[Dict[str, Any]] = []
    for it in items:
        ph = it["slot"].split(".")[0]
        if not phases or phases[-1]["phase"] != ph:
            phases.append({"phase": ph, "done": 0, "total": 0})
        phases[-1]["total"] += 1
        phases[-1]["done"] += 1 if it["done"] else 0
    open_items = [{"slot": it["slot"], "title": it["title"],
                   "followups": len(riding.get(it["slot"], [])),
                   "by_severity": {sev: sum(1 for r in riding.get(it["slot"], []) if r["severity"] == sev)
                                   for sev in SEVERITIES},
                   # W478 — the rows' total open priority, and the highest-priority rows first
                   "open_priority": round(sum(r["priority"]["score"] for r in riding.get(it["slot"], [])), 1),
                   "top": [{"id": r["id"], "score": r["priority"]["score"], "area": r["priority"]["area"],
                            "tier": r["priority"]["tier"]} for r in riding.get(it["slot"], [])[:5]]}
                  for it in _open_items(items)]
    return {"readable": bool(items),
            "next": open_items[0] if open_items else None, "open_items": open_items, "phases": phases,
            "done": sum(p["done"] for p in phases), "total": sum(p["total"] for p in phases),
            "followups": s["counts"], "unscheduled": [r["id"] for r in s["unscheduled"]],
            "priority": s["priority"]}



# ── W486: the pace the plan is actually moving at ────────────────────────────
# The Owner asked to be able to see where this is going without asking. Everything below is
# MEASURED from the register itself — which round closed each row (`closed_by`) and which round
# found it (the `W###` in `source`/`found`) — and the projection is stated in ROUNDS, because a
# round is the unit the register can count. It does not know how long a round takes; the CLI adds
# that separately from git, and says so.
#
# The honesty rules this obeys, which are the whole point of it:
#   · a rate measured over fewer than MIN_OBSERVED build rounds is `not assessable`, not a guess;
#   · if the backlog is NOT shrinking (rows found per round >= rows closed per round) no completion
#     is projected at all — the answer is "not at this rate", with the two numbers shown;
#   · the projection is arithmetic over an observed mean, and it says so in `basis`. It is not a
#     promise, a deadline, or a date.
FORECAST_WINDOW = 6          # the most recent build rounds the rate is measured over
MIN_OBSERVED = 3             # fewer than this and the rate is not assessable


def _round_activity(register: Any) -> Dict[str, Dict[str, int]]:
    """{round_id: {closed, found}} from the register's own record of each row."""
    import re as _re
    act: Dict[str, Dict[str, int]] = {}

    def _slot(rid: str) -> Dict[str, int]:
        return act.setdefault(rid, {"closed": 0, "found": 0})

    for r in raw_items(register):
        if not isinstance(r, dict):
            continue
        by = str(r.get("closed_by") or "").strip()
        if by and _re.fullmatch(r"W\d{3}", by):
            _slot(by)["closed"] += 1
        m = _re.search(r"\bW(\d{3})\b", f"{r.get('source') or ''} {r.get('found') or ''}")
        if m:
            _slot("W" + m.group(1))["found"] += 1
    return act


def _item_activity(register: Any) -> Dict[str, Dict[str, int]]:
    """{slot: {round_id: rows closed}} - the closure record PER PLAN ITEM.

    W493 (the C4/C10 rule turned on the planner itself): the projection for a single item divided THAT
    item's open rows by the rate measured over the WHOLE register, so the figure was arithmetic over a
    population the label did not name. The gate P1.18 read "35 open rows ~ 4 rounds" while the same
    six-round window this rate uses closed 16 of its rows - 2.67 per round, about fourteen rounds. A
    class-wide batch closes rows across five or six items at once, so the overall rate is three to five
    times any single item's. An item is projected at ITS OWN rate or it is not projected.

    Both numbers are measured over the SAME window as the overall rate, so the two are comparable; a
    figure quoted over a different span of rounds would repeat the defect in the fix's own notes."""
    import re as _re
    per: Dict[str, Dict[str, int]] = {}
    for r in raw_items(register):
        if not isinstance(r, dict):
            continue
        by = str(r.get("closed_by") or "").strip()
        if not (by and _re.fullmatch(r"W\d{3}", by)):
            continue
        # a closed row keeps the item it rode in `slot`; `item` is cleared when it closes
        slot = str(r.get("slot") or r.get("item") or "").strip()
        if not slot:
            continue
        per.setdefault(slot, {})
        per[slot][by] = per[slot].get(by, 0) + 1
    return per


def forecast(register: Any, prompt_text: str, window: int = FORECAST_WINDOW) -> Dict[str, Any]:
    """What the plan's own record says about its pace, and what that projects — or why it cannot."""
    items = plan_items(prompt_text)
    s = schedule(register if isinstance(register, dict) else {"items": []}, prompt_text)
    riding = {x["slot"]: x["items"] for x in s["schedule"]}
    act = _round_activity(register)

    # A BUILD round is one that closed at least one row. Rounds that only registered findings (a
    # sweep, an interrogation) are counted as what they were — they add work, they do not burn it.
    build = sorted([r for r, a in act.items() if a["closed"] > 0])
    recent = build[-window:]
    closed = [act[r]["closed"] for r in recent]
    found = [act[r]["found"] for r in recent]
    n = len(recent)
    per_round_closed = round(sum(closed) / n, 2) if n else 0.0
    per_round_found = round(sum(found) / n, 2) if n else 0.0
    net = round(per_round_closed - per_round_found, 2)

    # A ONE-TIME INTAKE is a round that registered findings far beyond the usual — an audit, a sweep,
    # an interrogation of an outside proposal. W477 alone registered 100 rows. Averaging that into an
    # ongoing rate says the backlog grows forever, which is as untrue as ignoring it. Both numbers are
    # reported, the excluded rounds are NAMED, and neither is presented as the real one on its own.
    _med = sorted(found)[n // 2] if n else 0
    _spikes = [r for r in recent if act[r]["found"] > max(3 * _med, 10)]
    steady = [r for r in recent if r not in _spikes]
    sn = len(steady)
    steady_closed = round(sum(act[r]["closed"] for r in steady) / sn, 2) if sn else 0.0
    steady_found = round(sum(act[r]["found"] for r in steady) / sn, 2) if sn else 0.0
    steady_net = round(steady_closed - steady_found, 2)

    open_rows = [r for slot in s["schedule"] for r in slot["items"]]
    open_items = _open_items(items)
    nxt = open_items[0] if open_items else None
    next_open = len(riding.get(nxt["slot"], [])) if nxt else 0

    # The projection uses the STEADY rate (one-time intakes excluded) and says so; with none
    # excluded the two are the same number.
    _rate, _rnet, _rn = (steady_closed, steady_net, sn) if sn >= MIN_OBSERVED else (per_round_closed, net, n)

    def _rounds_for(rows: int) -> Optional[int]:
        if _rn < MIN_OBSERVED or _rate <= 0 or _rnet <= 0:
            return None
        import math as _math
        return int(_math.ceil(rows / _rate))

    # W493 - an ITEM is projected at the rate measured on ITS OWN rows, over the same window of rounds
    # that closed anything. Dividing one item's backlog by the whole register's rate is a projection
    # about a population the label does not name: it made the current gate read four rounds when its
    # own record says eighteen. Too little history on an item means NO number, never a borrowed one.
    _per_item = _item_activity(register)

    def _item_rate(slot: str) -> Dict[str, Any]:
        rec = _per_item.get(slot) or {}
        mine = [rec.get(r, 0) for r in recent]          # the same rounds the overall rate uses
        rounds_closing = [r for r in recent if rec.get(r, 0) > 0]
        n_mine = len(rounds_closing)
        rate = round(sum(mine) / len(recent), 2) if recent else 0.0
        return {"rate": rate, "rounds_closing": rounds_closing, "closed_in_window": sum(mine),
                "assessable": bool(n_mine >= MIN_OBSERVED and rate > 0)}

    def _item_projection(slot: str, rows: int) -> Dict[str, Any]:
        ir = _item_rate(slot)
        if rows <= 0:
            return {"rounds_projected": 0, "rate_used": ir["rate"],
                    "basis": "no open row rides this item"}
        if not ir["assessable"]:
            return {"rounds_projected": None, "rate_used": ir["rate"],
                    "basis": (f"not projected: only {len(ir['rounds_closing'])} of the last "
                              f"{len(recent)} build round(s) closed a row on {slot} "
                              f"(a rate needs {MIN_OBSERVED}); the overall rate is measured over "
                              f"every item's rows and is not this item's")}
        import math as _math
        return {"rounds_projected": int(_math.ceil(rows / ir["rate"])),
                "rate_used": ir["rate"],
                "basis": (f"at {slot}'s OWN rate: {ir['closed_in_window']} row(s) over the last "
                          f"{len(recent)} build round(s) = {ir['rate']}/round")}

    assessable = _rn >= MIN_OBSERVED and _rate > 0
    if not assessable:
        why = (f"only {n} build round(s) on record — a rate needs at least {MIN_OBSERVED}"
               if n < MIN_OBSERVED else "no round on record has closed a row")
    elif _rnet <= 0:
        why = (f"the backlog is not shrinking: the last {_rn} build rounds closed {_rate} rows each "
               f"and registered {steady_found if sn >= MIN_OBSERVED else per_round_found}, a net of "
               f"{_rnet} per round. No completion is projected at this rate")
    else:
        why = None

    return {
        "assessable": bool(assessable and _rnet > 0),
        "not_assessable_because": why,
        "window": {"rounds": recent, "count": n,
                   "closed_per_round": per_round_closed, "found_per_round": per_round_found,
                   "net_per_round": net},
        # the same window with one-time intakes (audits, sweeps, interrogations) taken out and named
        "steady": {"rounds": steady, "count": sn, "excluded": _spikes,
                   "closed_per_round": steady_closed, "found_per_round": steady_found,
                   "net_per_round": steady_net},
        "rate_used": {"closed_per_round": _rate, "net_per_round": _rnet, "rounds": _rn,
                      "source": ("steady (one-time intakes excluded)" if sn >= MIN_OBSERVED
                                 else "the whole window")},
        "open_rows": len(open_rows),
        "next_item": (None if not nxt else dict(
            {"slot": nxt["slot"], "title": nxt["title"], "open_rows": next_open},
            **_item_projection(nxt["slot"], next_open))),
        "by_item": [dict({"slot": it["slot"], "open_rows": len(riding.get(it["slot"], []))},
                         **_item_projection(it["slot"], len(riding.get(it["slot"], []))))
                    for it in open_items],
        "items": {"done": sum(1 for i in items if i["done"]), "total": len(items),
                  "open": len(open_items)},
        "all_rows_rounds_projected": _rounds_for(len(open_rows)),
        "basis": ("measured from the register: which round closed each row and which round found it. "
                  f"The rate is the mean over the last {n} round(s) that closed anything, ACROSS EVERY "
                  "ITEM - a class-wide batch closes rows on five or six items at once, so no single "
                  "item moves at this rate. ALL OPEN ROWS uses it because it covers the same "
                  "population; each ITEM is projected at the rate measured on its own rows, or not "
                  "projected at all. A projection "
                  "is arithmetic over that mean, in ROUNDS — the register does not record how long a "
                  "round takes, and this is not a date, a deadline or a promise. Rounds that only "
                  "registered findings are counted as finding work, never as burning it."),
    }


def render_forecast(register: Any, prompt_text: str) -> str:
    """The same facts as one readable block for the plan documents."""
    f = forecast(register, prompt_text)
    w = f["window"]
    out = [f"WHERE THIS IS GOING (generated — {f['items']['done']} of {f['items']['total']} plan entries done, "
           f"{f['open_rows']} open rows)"]
    out.append(f"  PACE, over the last {w['count']} round(s) that closed anything ({', '.join(w['rounds']) or 'none'}): "
               f"{w['closed_per_round']} rows closed per round, {w['found_per_round']} found, net {w['net_per_round']}.")
    st = f["steady"]
    if st["excluded"]:
        out.append(f"  ONE-TIME INTAKE excluded from the rate: {', '.join(st['excluded'])} "
                   f"(an audit, sweep or interrogation registers findings; it does not burn them). "
                   f"Steady rate over {st['count']} round(s): {st['closed_per_round']} closed, "
                   f"{st['found_per_round']} found, net {st['net_per_round']}.")
    out.append(f"  RATE USED: {f['rate_used']['closed_per_round']} rows/round — {f['rate_used']['source']}.")
    if not f["assessable"]:
        out.append(f"  NO PROJECTION: {f['not_assessable_because']}.")
    else:
        nx = f["next_item"]
        if nx:
            # W493 — this said "at the observed rate", meaning the whole register's; the gate's own
            # record is three to five times slower because a class-wide batch spreads across items.
            out.append(f"  NEXT — {nx['slot']}: {nx['open_rows']} open rows "
                       + (f"\u2248 {nx['rounds_projected']} round(s) \u2014 {nx['basis']}."
                          if nx["rounds_projected"] is not None else f"\u2014 {nx['basis']}."))
        out.append(f"  ALL OPEN ROWS: {f['open_rows']} \u2248 {f['all_rows_rounds_projected']} round(s) at the "
                   f"overall rate, which covers every item's rows.")
        rest = [x for x in f["by_item"] if x["open_rows"] > 0][:8]
        out.append("  BY ITEM (each at its OWN measured rate; \u2014 = too few rounds have closed one of its "
                   "rows to measure): "
                   + " \u00b7 ".join(f"{x['slot']} {x['open_rows']}r"
                                 + (f"\u2248{x['rounds_projected']}" if x["rounds_projected"] is not None else "\u2014")
                                 for x in rest))
    # W487 — the pace says how fast; the batch says what to run next to make it faster. A reader who
    # sees only the projection has no lever; naming the largest closable batch beside it gives one.
    try:
        _b = batches(register, prompt_text)["batches"]
    except Exception:
        _b = []
    if _b:
        _t = _b[0]
        out.append(f"  BIGGEST BATCH: {_t['class']} ({_t['what']}) — one mechanism closes "
                   f"{_t['closes_count']} row(s) across {_t['files_count']} file(s)"
                   + (f", advancing {_t['partial_count']} more" if _t["partial_count"] else "")
                   + f". Items: {', '.join(_t['slots'])}.")
    out.append("  This is arithmetic over an observed mean, in rounds. It is not a date and not a promise;")
    out.append("  it moves every time a round closes or registers a row.")
    return "\n".join(out)


# ── W487: which ROUND to run — the batch, not the row ────────────────────────
# The truth sweep (W477) recorded every finding under one of ten CLASSES, and the register's rows cite
# them. A row is one emitting FILE; a class runs ACROSS files. That mismatch is why rounds that pick
# the next row close two or three, and the round that built one rule and swept every consumer closed
# seven. This proposes the batch: the class whose rows one mechanism can close, largest first.
#
# It is a SUGGESTION beside the plan's order, exactly as `suggested_order` is — the gate still decides
# which item is open, and a row's own priority still decides within a batch. And it never claims a
# batch will close a row it cannot: a row citing more than one class is listed as PARTIAL, because
# fixing one of its classes leaves it open, and the count says so.
SWEEP_CLASSES = {
    "C1": "certifies what it could not assess",
    "C2": "keyword screen presented as a judgement",
    "C3": "invented or constant readings",
    "C4": "present-tense claims about processes not running",
    "C5": "a second writer or the reached page disagrees with the API",
    "C6": "faith-content fidelity",
    "C7": "missing provenance",
    "C8": "figures that cannot fail",
    "C9": "a decision that breaks its own rule",
    "C10": "counts or lists that do not match what is served",
}
# W489 — a class is counted only where the row CITES it in the sweep's own evidence form, never
# wherever the two characters happen to appear in prose. The first form read `\bC(\d{1,2})\b` across
# the whole of title+why, so a row that merely DISCUSSED a class — "C3 (invented or constant
# readings) closes 4 rows inside P1.18 and 12 across all items" — was counted into C1, C3 and C7 and
# swelled three batches it had no defect in. A batch count that includes rows by accident is the same
# defect the batch is for: a figure presented as a measurement of something it did not measure.
#   The two forms the sweep actually writes:
#     title — "sweep products.py: 3 Tier-1 truth defects (C3,C4,C7) — …"   a parenthesised class list
#     why   — "S12.1 C3: …"                                                a sweep id, then the class
#     why   — "lists S1.1 (C3, VSB Cockpit …) and S8.1 (C8, …)"            a sweep id, then (class, prose)
# The three forms were read off the rows that exist, not guessed: narrowing to the first two alone
# silently dropped FU-231's two real citations, which is the same defect in the other direction.
_CLASS_LIST_RE = re.compile(r"\(\s*C\d{1,2}(?:\s*,\s*C\d{1,2})*\s*\)")
_CLASS_IN_LIST_RE = re.compile(r"C(\d{1,2})")
_CLASS_CITE_RE = re.compile(r"\bS\d{1,3}(?:\.\d{1,3})?\s*\(?\s*C(\d{1,2})\b")


def row_classes(row: Dict[str, Any]) -> List[str]:
    """The sweep classes a row's own evidence CITES, in the sweep's own citation form. Empty when it
    cites none — an older row, or one from a ledger pass rather than the sweep; never guessed at, and
    never inferred from a class name merely mentioned in the row's prose (W489)."""
    text = f"{row.get('title') or ''} {row.get('why') or ''}"
    found = {f"C{m}" for lst in _CLASS_LIST_RE.findall(text) for m in _CLASS_IN_LIST_RE.findall(lst)}
    found |= {f"C{m}" for m in _CLASS_CITE_RE.findall(text)}
    return sorted((c for c in found if c in SWEEP_CLASSES), key=lambda c: int(c[1:]))


def batches(register: Any, prompt_text: str, slot: Optional[str] = None) -> Dict[str, Any]:
    """Group the open rows into rounds one mechanism could serve, largest closable first."""
    s = schedule(register if isinstance(register, dict) else {"items": []}, prompt_text)
    rows = [r for x in s["schedule"] for r in x["items"] if not slot or r["slot"] == slot]
    by_id = {r["id"]: r for r in rows}
    raw = {r.get("id"): r for r in raw_items(register) if isinstance(r, dict)}

    groups: Dict[str, Dict[str, Any]] = {}
    unclassed: List[str] = []
    for r in rows:
        cs = row_classes(raw.get(r["id"], {}))
        if not cs:
            unclassed.append(r["id"])
            continue
        for c in cs:
            g = groups.setdefault(c, {"class": c, "what": SWEEP_CLASSES[c],
                                      "closes": [], "partial": [], "files": set(), "slots": set()})
            (g["closes"] if len(cs) == 1 else g["partial"]).append(r["id"])
            g["files"].update(normalise_path(f) for f in (raw.get(r["id"], {}).get("files") or []))
            g["slots"].add(r["slot"])

    out = []
    for g in groups.values():
        closes, partial = g["closes"], g["partial"]
        files = sorted(g["files"])
        score = round(sum(by_id[i]["priority"]["score"] for i in closes), 1)
        out.append({
            "class": g["class"], "what": g["what"],
            # rows this batch CLOSES: their evidence cites this class and nothing else
            "closes": sorted(closes), "closes_count": len(closes),
            # rows it advances but cannot close: they cite other classes too, and say so
            "partial": sorted(partial), "partial_count": len(partial),
            "files": files, "files_count": len(files),
            "slots": sorted(g["slots"]),
            "priority_closed": score,
            # the whole point: rows closed per file the round has to touch
            "rows_per_file": round(len(closes) / len(files), 2) if files else 0.0,
        })
    out.sort(key=lambda b: (-b["closes_count"], -b["priority_closed"]))
    return {
        "batches": out,
        "unclassed": sorted(unclassed),
        "unclassed_count": len(unclassed),
        "rows": len(rows),
        "basis": ("grouped by the sweep class each row's own evidence cites (W477's ten). `closes` are "
                  "rows citing ONLY this class \u2014 one mechanism can finish them; `partial` cite others too, "
                  "so this batch advances them without closing them, and they are counted separately. "
                  "Rows citing no class are listed, never guessed at. A suggestion beside the plan's "
                  "order, not a replacement for it: the gate still decides which item is open."),
    }


def render_batches(register: Any, prompt_text: str, slot: Optional[str] = None, top: int = 5) -> str:
    b = batches(register, prompt_text, slot)
    head = f"NEXT ROUNDS BY BATCH (generated \u2014 {b['rows']} open row(s)"
    head += f" on {slot}" if slot else ""
    out = [head + f"; {b['unclassed_count']} cite no sweep class)"]
    if not b["batches"]:
        out.append("  No row in scope cites a sweep class, so no batch can be proposed from the evidence.")
    for x in b["batches"][:top]:
        out.append(f"  {x['class']} \u2014 {x['what']}: closes {x['closes_count']} row(s) across "
                   f"{x['files_count']} file(s) ({x['rows_per_file']} per file)"
                   + (f", advances {x['partial_count']} more" if x["partial_count"] else "")
                   + f" \u00b7 {', '.join(x['slots'])}")
    out.append("  A batch is one mechanism swept across every file that consumes it. Rows citing more")
    out.append("  than one class are advanced, not closed \u2014 counted separately, never as progress.")
    return "\n".join(out)

def _wrap(prefix: str, parts: List[str], indent: str = "    ", width: int = 112) -> List[str]:
    lines, cur = [], prefix
    for i, part in enumerate(parts):
        piece = part + (" · " if i < len(parts) - 1 else "")
        if len(cur) + len(piece) > width and cur.strip():
            lines.append(cur.rstrip())
            cur = indent
        cur += piece
    lines.append(cur.rstrip())
    return lines


def render_plan_now(register: Any, prompt_text: str) -> str:
    """The PLAN NOW block both docs carry (plain text, LF). Every line is indented or starts with a word, so no line
    can ever be read as a plan item (" P1.13 …")."""
    p = plan_now(register, prompt_text)
    c = p["followups"]
    out = ["PLAN NOW — generated from the delivery plan's items and docs/FOLLOWUPS.json by scripts/followups.py on",
           "every register change (add · close · drop · reslot · route · done · render); never edit between the markers."]
    nxt = p["next"]
    if not p["readable"]:
        out.append("  The delivery plan could not be read: no items were found in its <delivery_plan> section, so")
        out.append("  nothing below says what is next or done — repair the section (check names the problem).")
    elif nxt is None:
        out.append("  Next: every delivery-plan item is done.")
    else:
        riders = nxt["followups"]
        out.append(f"  Next: {nxt['slot']} {nxt['title']} — "
                   + (f"{riders} follow-up{'s' if riders != 1 else ''} ride it." if riders else "no follow-ups ride it."))
        rest = [f"{it['slot']} {it['followups']}" for it in p["open_items"][1:]]
        if rest:
            out.extend(_wrap("  Then, in order (the follow-ups riding each): ", rest))
    if nxt is not None and nxt["top"]:
        # W478 — what to do first inside the next item: its highest-priority rows (python scripts/followups.py priority)
        out.extend(_wrap(f"  Highest priority in {nxt['slot']} (score · area): ",
                         [f"{t['id']} {t['score']} {t['area'] or 'unmapped'}" for t in nxt["top"]]))
    out.append(f"  Done: {p['done']} of {p['total']} items — "
               + " · ".join(f"{ph['phase']} {ph['done']}/{ph['total']}" for ph in p["phases"]) + ".")
    comp = p["priority"]["completion"]
    gate = p["priority"]["gate_phase"]
    gp = comp["by_phase"].get(gate) if gate else None
    if gp is not None and gp["weighted_pct"] is not None:
        # (refutation) it measures the follow-up ROWS, not plan items — said so, beside the item count above it
        out.append(f"  Follow-up completion weighted by priority — {gate}: {gp['weighted_pct']}% of its rows' priority "
                   f"closed ({gp['rows_closed']} of {gp['rows_closed'] + gp['rows_open']} rows); every phase's rows: "
                   f"{comp['overall_weighted_pct']}% (the retired pre-plan queue left out).")
    if p["priority"]["config_problems"]:
        out.append("  PRIORITY WEIGHTS UNREADABLE — the defaults serve: " + p["priority"]["config_problems"][0])
    out.append(f"  Follow-ups: {c['open']} open — {c['scheduled']} ride a plan item ({c['high']} high), "
               f"{c['unscheduled']} unscheduled, {c['awaiting_owner']} awaiting the Owner; {c['done']} done, "
               f"{c['dropped']} dropped.")
    if p["unscheduled"]:
        out.extend(_wrap("  UNSCHEDULED — slot each to a plan item (python scripts/followups.py reslot FU-… --slot auto): ",
                         p["unscheduled"]))
    return "\n".join(out)


# indented two spaces so no rendered line can ever match the plan's " P1.12 …" item lines
def _row_line(r: Dict[str, Any]) -> str:
    pr = r.get("priority")
    p = f" [p {pr['score']}]" if isinstance(pr, dict) else ""        # W478 — the row's priority where it is scheduled
    return f"    {r['id']} [{r['severity']}]{p} {r['title']} — {r['why']} (found {r['source']})"


def render(register: Dict[str, Any], prompt_text: str) -> str:
    """The block both docs carry between the markers (plain text, LF; splice converts per doc)."""
    s = schedule(register, prompt_text)
    c = s["counts"]
    out = [
        "SCHEDULED FOLLOW-UPS — every task a round finds and does not do is a row in docs/FOLLOWUPS.json, added in",
        "the same commit (python scripts/followups.py add routes it to the plan item that owns its area; a high one",
        "rides the next open item) or slotted OWNER (waits on an Owner decision; never scheduled). A round that",
        "finishes an item marks it with python scripts/followups.py done P1.13 --by W### — its rows move along the",
        "routes or are closed first; the suite fails on a row left on a finished item.",
        f"Open {c['open']} ({c['scheduled']} scheduled, {c['high']} high · {c['unscheduled']} unscheduled · "
        f"{c['awaiting_owner']} awaiting the Owner) · done {c['done']} · dropped {c['dropped']}.",
    ]
    if not s["schedule"]:
        out.append("  (nothing scheduled)")
    for slot in s["schedule"]:
        out.append(f"  {slot['slot']} — {slot['title']}")
        out.extend(_row_line(r) for r in slot["items"])
    if s["unscheduled"]:
        out.append("  UNSCHEDULED — riding no open plan item; slot each (python scripts/followups.py reslot FU-… --slot auto):")
        out.extend(_row_line(r) + f" [slot {r['slot']}]" for r in s["unscheduled"])
    if s["awaiting_owner"]:
        out.append("  AWAITING THE OWNER — recorded, never scheduled into a round without the Owner's instruction:")
        out.extend(_row_line(r) for r in s["awaiting_owner"])
    return "\n".join(out)


def _marker_problem(text: str, name: str, begin: str = BEGIN, end: str = END) -> Optional[str]:
    b, e = text.count(begin), text.count(end)
    kind = "PLAN NOW" if begin == PLAN_BEGIN else "follow-up"
    if b != 1 or e != 1 or text.index(begin) > text.index(end):
        return f"{name} must carry exactly one {kind} marker pair (found {b} begin, {e} end)"
    return None


def _block(text: str, begin: str = BEGIN, end: str = END) -> Optional[str]:
    if _marker_problem(text, "doc", begin, end):
        return None
    return text.split(begin, 1)[1].split(end, 1)[0].replace("\r\n", "\n").strip("\n")


def splice(text: str, block: str, begin: str = BEGIN, end: str = END) -> str:
    """Replace a marker block in a doc, preserving that doc's line endings. Refuses a doc whose markers are missing or
    duplicated — a second, stale copy would never be compared or re-rendered."""
    bad = _marker_problem(text, "the doc", begin, end)
    if bad:
        raise ValueError(bad)
    crlf = "\r\n" in text
    new = "\n" + block + "\n"
    if crlf:
        new = new.replace("\n", "\r\n")
    head, tail = text.split(begin, 1)
    return head + begin + new + end + tail.split(end, 1)[1]


def splice_all(text: str, register: Any, prompt_text: str) -> str:
    """Both generated blocks, rendered from the register and the (possibly new) delivery plan text."""
    text = splice(text, render(register, prompt_text))
    text = splice(text, render_plan_now(register, prompt_text), PLAN_BEGIN, PLAN_END)
    return splice(text, render_forecast(register, prompt_text), PACE_BEGIN, PACE_END)


def mark_done(prompt_text: str, slot: str, round_id: str) -> str:
    """W469 — mark a delivery-plan item done the one way check() reads: '✅ DONE W###' right after its id, on its own
    line inside <delivery_plan>. Refuses an unknown, duplicated or already-done item, or a malformed round."""
    if not _ROUND.match(round_id or ""):
        raise ValueError(f"the round must look like W469 (not {round_id!r})")
    items = [it for it in plan_items(prompt_text) if it["slot"] == slot]
    if len(items) != 1:
        raise ValueError(f"{slot} appears {len(items)} times in the delivery plan")
    if items[0]["done"]:
        raise ValueError(f"{slot} is already DONE {items[0]['done_by']}")
    if items[0]["malformed_done"]:
        raise ValueError(f"{slot}'s line already says done in another form — repair it by hand first")
    m = re.search(r"^<delivery_plan>[ \t]*\r?$(.*?)^</delivery_plan>[ \t]*\r?$", prompt_text, flags=re.M | re.S)
    start, end = m.span(1)
    body = prompt_text[start:end]
    hits = list(re.finditer(r"^ " + re.escape(slot) + r"(?=\s)", body, flags=re.M))
    outside = [h for h in hits if not _inside_blocks(body, h.start())]
    if len(outside) != 1:
        raise ValueError(f"{slot}'s line could not be found exactly once in the delivery plan")
    at = start + outside[0].end()
    return prompt_text[:at] + f" ✅ DONE {round_id}" + prompt_text[at:]


def _inside_blocks(text: str, pos: int) -> bool:
    for begin, end in ((BEGIN, END), (PLAN_BEGIN, PLAN_END)):
        for m in re.finditer(re.escape(begin) + r".*?" + re.escape(end), text, flags=re.S):
            if m.start() <= pos < m.end():
                return True
    return False


def normalise_path(f: str) -> str:
    f = f.strip().replace("\\", "/")
    while f.startswith("./"):
        f = f[2:]
    return f


def _tracked(root: Path) -> Optional[Set[str]]:
    try:
        out = subprocess.run(["git", "ls-files", "-z"], cwd=str(root), capture_output=True, timeout=20)
        if out.returncode == 0:
            return {p for p in out.stdout.decode("utf-8", "replace").split("\0") if p}
    except (OSError, subprocess.SubprocessError):
        pass
    return None


def _exists_exact(root: Path, rel: str) -> bool:
    # each component with its exact case (Windows would otherwise accept any case), and a FILE at the end
    cur = root
    for part in rel.split("/"):
        try:
            if part not in {p.name for p in cur.iterdir()}:
                return False
        except OSError:
            return False
        cur = cur / part
    return cur.is_file()


def check(register: Any, prompt_text: str, living_text: Optional[str] = None,
          root: Optional[Path] = None) -> List[str]:
    """Every problem with the register and its two rendered copies, as sentences. Never raises on a
    malformed register — a problem is reported, not hidden behind a traceback."""
    root = root or ROOT
    problems: List[str] = []
    body = delivery_plan_body(prompt_text)
    items = plan_items(prompt_text)
    if body is None or not items:
        return ["the delivery plan has no <delivery_plan> section with items to slot follow-ups into"]
    for it in items:
        if it["malformed_done"]:
            problems.append(f"plan item {it['slot']} says done, but not as '✅ DONE W###' right after its id — "
                            "the register cannot tell whether it is done")
    counts: Dict[str, int] = {}
    for it in items:
        counts[it["slot"]] = counts.get(it["slot"], 0) + 1
    problems += [f"plan item {s} appears {n} times in the delivery plan" for s, n in counts.items() if n > 1]
    by_slot = {i["slot"]: i for i in items}

    if not isinstance(register, dict) or not isinstance(register.get("items"), list):
        return problems + ["the register must be an object with an items list"]
    raw = register["items"]
    for i, r in enumerate(raw):
        problems += _row_shape_problems(r, i)         # reported; the row is skipped below, the rules still run
    rows = _rows(register)

    numbers: Dict[int, List[str]] = {}
    for r in raw:
        if isinstance(r, dict) and id_number(r.get("id")) is not None:
            numbers.setdefault(id_number(r.get("id")), []).append(str(r.get("id")))
    problems += [f"{ids[0]}: duplicate id ({', '.join(repr(x) for x in ids)})" for ids in numbers.values() if len(ids) > 1]

    tracked = _tracked(root) if any(r["status"] == "open" and r["files"] for r in rows) else None
    for r in rows:
        rid = r["id"]
        if not _ID.match(rid):
            problems.append(f"{rid}: id must look like FU-001")
        slot = r["slot"]
        if r["status"] == "done":
            if not _ROUND.match(r.get("closed_by") or ""):
                problems.append(f"{rid}: done without closed_by naming the round (W###)")
            continue
        if r["status"] == "dropped":
            if not (r.get("note") or "").strip():
                problems.append(f"{rid}: dropped without a note saying why")
            continue
        # open
        if r.get("closed_by"):
            problems.append(f"{rid}: open but closed_by is set ({r['closed_by']}) — close it or clear closed_by")
        if r["owner_gated"]:
            if slot != "OWNER":
                problems.append(f"{rid}: owner-gated work is slotted OWNER, never {slot} — it is not scheduled into a round")
        elif slot == "OWNER":
            problems.append(f"{rid}: slot OWNER but owner_gated is false")
        elif slot in RETIRED_SLOTS:
            problems.append(f"{rid}: slot {slot} is retired (W469) — a queue of its own rounds held the plan back; "
                            f"let the row ride the plan item that owns its area: python scripts/followups.py reslot "
                            f"{rid} --slot auto")
        elif slot not in by_slot:
            problems.append(f"{rid}: slot {slot} is not a delivery-plan item (nor OWNER)")
        elif by_slot[slot]["done"]:
            problems.append(f"{rid}: rides on {slot}, already DONE {by_slot[slot]['done_by']} — "
                            f"that round closed without doing it: close it, drop it with a reason, or re-slot it")
        for f in r["files"]:
            if f != normalise_path(f) or f.startswith("/") or re.match(r"^[A-Za-z]:", f):
                problems.append(f"{rid}: names {f!r} — use a repository-relative path with forward slashes")
            elif not _exists_exact(root, f):
                problems.append(f"{rid}: names {f}, which is not in the working tree — the row has gone stale")
            elif tracked is not None and f not in tracked:
                problems.append(f"{rid}: names {f}, which git does not track yet — git add it (CI only sees tracked files)")

    # W469 — routes: well-formed, naming a plan item that is still open (a finished item hands its area on)
    route_slots: Dict[str, int] = {}
    for i, rt in enumerate(raw_routes(register)):
        shape = _route_shape_problems(rt, i)
        if shape:
            problems += shape
            continue
        hf = rt.get("handed_from")
        if hf:
            origin = by_slot.get(hf)
            if origin is None:
                problems.append(f"the route to {rt['slot']} says it was handed from {hf}, which is not a delivery-plan item")
            elif not origin["done"]:
                problems.append(f"the route to {rt['slot']} says it was handed from {hf}, which is still open — an open "
                                "item does not hand its area away")
        else:                                          # W473 — a handed route is a second route by design
            route_slots[rt["slot"]] = route_slots.get(rt["slot"], 0) + 1
        target = by_slot.get(rt["slot"])
        if target is None:
            problems.append(f"the route to {rt['slot']} names no delivery-plan item")
        elif target["done"]:
            problems.append(f"the route to {rt['slot']} sends new rows to an item already DONE {target['done_by']} — "
                            f"hand its area on: python scripts/followups.py route --from {rt['slot']} --slot <open item> "
                            "(its routes become handed routes of that item, each in its own place)")
        for prefix in rt.get("files", []):
            if not prefix.endswith("/") and (root / prefix).is_dir():
                problems.append(f"the route to {rt['slot']} names the directory {prefix} without a trailing '/' — "
                                "as written it matches only a file of that exact name")
    problems += [f"{n} routes send rows to {s} — an item has one route of its own (a handed one carries handed_from): "
                 f"remove them (python scripts/followups.py route --slot {s} --remove) and add it back whole"
                 for s, n in route_slots.items() if n > 1]
    # W473 (register FU-070) — an item's text that lists rows drifts from the register: every FU id an OPEN item's
    # text names must be a row that rides that item (or a closed one); PLAN NOW is where riders are listed
    open_by_slot = {it["slot"]: it for it in items if not it["done"]}
    row_slot = {r["id"]: (r["slot"], r["status"]) for r in rows}
    for slot, text in _item_blocks(body).items():
        if slot not in open_by_slot:
            continue
        for fid in sorted(set(re.findall(r"\bFU-\d{3}\b", text))):
            where = row_slot.get(fid)
            if where and where[1] == "open" and where[0] not in (slot, "OWNER"):   # a gated row rides no item
                problems.append(f"{slot}'s text names {fid}, which rides {where[0]} — an item's text does not list its "
                                "rows (PLAN NOW does); say the area, not the id")
    if "routes" in register and not isinstance(register["routes"], list):
        problems.append("the register's routes must be a list")

    for text, name, lockstep, begin, end, rendered in (
            (prompt_text, "the delivery plan", LOCKSTEP_PROMPT, BEGIN, END, render),
            (living_text, "the living plan", LOCKSTEP_LIVING, BEGIN, END, render),
            (prompt_text, "the delivery plan", LOCKSTEP_PLAN_PROMPT, PLAN_BEGIN, PLAN_END, render_plan_now),
            (living_text, "the living plan", LOCKSTEP_PLAN_LIVING, PLAN_BEGIN, PLAN_END, render_plan_now),
            (prompt_text, "the delivery plan", LOCKSTEP_PACE_PROMPT, PACE_BEGIN, PACE_END, render_forecast),
            (living_text, "the living plan", LOCKSTEP_PACE_LIVING, PACE_BEGIN, PACE_END, render_forecast)):
        if text is None:
            continue
        bad = _marker_problem(text, name, begin, end)
        if bad:
            problems.append(bad)
            continue
        if _block(text, begin, end) != rendered(register, prompt_text):
            problems.append(lockstep)
    for begin, kind in ((BEGIN, "follow-up"), (PLAN_BEGIN, "PLAN NOW"), (PACE_BEGIN, "PACE")):
        if begin in prompt_text and begin not in body:
            problems.append(f"the delivery plan's {kind} block must sit inside the <delivery_plan> section")
    # W478 — the priority weights: a file that cannot be read or is malformed is a problem, never a silent default
    from agentic_core import plan_priority as pp
    cfg_, cfg_problems_ = pp.load_config(root)
    problems += cfg_problems_
    for i, r in enumerate(raw_items(register)):
        if isinstance(r, dict):                  # every row: completion scores closed rows with the same fields
            problems += [f"{r.get('id', f'row {i + 1}')}: {m}" for m in pp.row_field_problems(r, cfg_)]
    return problems
