import React from 'react';

interface MetricCardProps {
    label: string;
    /** null means nothing measured this — it is NOT zero and must never render as a number. */
    value: number | null;
    unit: string;
    borderClass: string;
}

const MetricCard: React.FC<MetricCardProps> = ({ label, value, unit, borderClass }) => (
    <div className={`p-4 rounded-lg bg-slate-900 border ${borderClass} min-w-[150px]`}>
        <div className="text-xs text-slate-500 uppercase tracking-wider font-bold">{label}</div>
        <div className="text-2xl font-black text-white mt-1">
            {value === null
                ? <span className="text-sm text-slate-600">NOT MEASURED</span>
                : `${value.toFixed(1)}${unit}`}
        </div>
    </div>
);

// W415 — this component fabricated its entire payload. A useEffect ran every 3 seconds and set
//     sentience:  85 + Math.random() * 10,   compliance: 98 + Math.random() * 2,
//     throughput: 12 + Math.random() * 5,    load:       45 + Math.random() * 20,
//     stability:  95 + Math.random() * 5
// which rendered as "Compliance 99.4%", "System Sentience 91.2%", "Stability 97.8%" under the
// heading "Organism Health Vitals" — a compliance percentage produced by a random number
// generator, refreshed on a timer precisely so it reads as live telemetry.
// Nothing measures any of the five. The real host vitals at GET /api/v138/ceo/vitals are the
// machine's CPU and memory, not organism sentience/throughput/stability, so feeding them in here
// would only relabel a real number as something it is not — the metaphor-metric defect fixed on
// CapitalDashboard (W405). The cards stay rather than being deleted, and state their absence.
const OrganismVitals: React.FC = () => {
    return (
        <div className="p-5 bg-black/90 text-white rounded-xl">
            <h2 className="mb-5 text-xs font-black uppercase tracking-widest border-l-4 border-green-400 pl-4">
                Organism Health Vitals
            </h2>
            <div className="flex gap-5 flex-wrap">
                <MetricCard label="System Sentience" value={null} unit="%" borderClass="border-cyan-400" />
                <MetricCard label="Compliance"       value={null} unit="%" borderClass="border-green-400" />
                <MetricCard label="Throughput"       value={null} unit=" t/m" borderClass="border-fuchsia-500" />
                <MetricCard label="Cognitive Load"   value={null} unit="%" borderClass="border-yellow-400" />
                <MetricCard label="Stability"        value={null} unit="%" borderClass="border-green-400" />
            </div>
            <p className="mt-5 text-[10px] text-slate-500 font-semibold leading-relaxed max-w-2xl">
                No telemetry source is connected to this panel. These five vitals were previously
                generated by <code>Math.random()</code> on a 3-second timer; they now show nothing
                until something real measures them.
            </p>
        </div>
    );
};

export default OrganismVitals;
