from .legacy import ScienceReactor
from .physics import PhysicsReactor
from .chemistry import ChemistryReactor
from .biology import BiologyReactor
from .compsci import CompSciReactor
from .materials import MaterialsReactor
from .astronomy import AstronomyReactor
from .math import MathReactor
from .interdisciplinary import InterdisciplinaryReactor
from .engineering import EngineeringReactor
from .environmental import EnvironmentalReactor
from .neuroscience import NeuroscienceReactor
