import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { ShieldAlert, Check, X, Sparkles } from 'lucide-react';

export const EvolutionProposals: React.FC = () => {
  const [proposals, setProposals] = useState<any[]>([]);

  useEffect(() => {
    axios.get('/api/v191/evolution/proposals').then(res => setProposals(res.data));
  }, []);

  const handleApprove = async (id: string) => {
    await axios.post(`/api/v191/evolution/proposals/${id}/approve`);
    setProposals(proposals.filter(p => p.id !== id));
  };

  const handleVote = async (id: string) => {
    await axios.post(`/api/v200/contribute/vote?proposal_id=${id}`);
    alert("Resonance Recorded. Your vote has been merged into the Merkle-DAG.");
  };

  return (
    <div className="space-y-10">
      <header>
        <h1 className="text-4xl font-black mb-2">Enhancement Proposer</h1>
        <p className="text-slate-500">Autonomous self-improvement proposals generated by the VSB AI CEO.</p>
      </header>

      <div className="space-y-6">
        {proposals.map(p => (
          <div key={p.id} className="p-8 rounded-3xl bg-slate-900/40 border border-slate-800 flex flex-col md:flex-row gap-8 items-start md:items-center">
            <div className="p-4 rounded-2xl bg-highlight/10 text-highlight flex-shrink-0">
              <Sparkles size={32} />
            </div>
            <div className="flex-1">
              <div className="flex items-center gap-3 mb-2">
                <span className="text-[10px] font-black uppercase px-2 py-0.5 rounded bg-slate-800 text-slate-400 border border-slate-700">
                  {p.type}
                </span>
                <span className="text-[10px] font-black uppercase text-rose-400">Impact: {p.impact}</span>
              </div>
              <h3 className="text-xl font-bold mb-2">{p.title}</h3>
              <p className="text-sm text-slate-400 max-w-2xl">{p.description}</p>
            </div>
            <div className="flex gap-4 flex-shrink-0">
              <button
                onClick={() => handleVote(p.id)}
                className="px-6 py-4 border border-slate-700 rounded-xl text-xs font-bold uppercase text-slate-400 hover:border-aura hover:text-white transition-all"
              >
                Vote
              </button>
              <button
                onClick={() => setProposals(proposals.filter(x => x.id !== p.id))}
                className="p-4 bg-slate-800 rounded-xl text-slate-400 hover:text-white transition-colors"
              >
                <X size={20} />
              </button>
              <button
                onClick={() => handleApprove(p.id)}
                className="flex items-center gap-2 px-8 py-4 bg-aura text-sovereign font-bold rounded-xl hover:scale-105 transition-all"
              >
                <Check size={20} />
                Approve Enhancement
              </button>
            </div>
          </div>
        ))}
        {proposals.length === 0 && (
          <div className="p-20 text-center border border-dashed border-slate-800 rounded-3xl text-slate-600">
            No pending evolution proposals. System is currently optimal.
          </div>
        )}
      </div>
    </div>
  );
};
