from typing import Protocol, Dict, Any, List, Optional

class IdentityProvider(Protocol):
    async def get_sovereign_id(self) -> str: ...
    async def sign_payload(self, payload: Dict[str, Any]) -> str: ...

class HardwareHAL(Protocol):
    async def run_inference(self, data: Any) -> Any: ...
    async def get_energy_metrics(self) -> Dict[str, float]: ...

class ExpressionEngine(Protocol):
    async def predict_phenotype(self, genotype: Dict[str, Any]) -> Dict[str, Any]: ...

class RegulationManager(Protocol):
    async def get_current_state(self) -> str: ... # REST, WORK, PLAY
    async def emit_signal(self, signal: str) -> None: ...

class ResilienceManager(Protocol):
    async def checkpoint(self, state: Dict[str, Any]) -> str: ...
    async def rollback(self, checkpoint_id: str) -> Dict[str, Any]: ...

class PropagationNode(Protocol):
    async def gossip(self, data: Dict[str, Any]) -> None: ...

class ModuleLibrary(Protocol):
    async def fetch_module(self, module_id: str) -> Any: ...

class RecombinationEngine(Protocol):
    async def merge_weights(self, weight_vectors: List[Dict[str, float]]) -> Dict[str, float]: ...

class OrchestratorAgent(Protocol):
    async def execute_task(self, task: Dict[str, Any]) -> Dict[str, Any]: ...

class EvolutionArena(Protocol):
    async def select_fittest(self, candidates: List[Any], scores: List[float]) -> Any: ...

class CivilisationFederation(Protocol):
    async def sync_embeddings(self, embeddings: List[float]) -> None: ...

class UserInterface(Protocol):
    async def render(self, data: Any, audience: str) -> None: ...
