facility_protocols:
  digital_engines:
    name: "Digital Engines"
    type: "Engine"
  reactors:
    name: "Validation Reactors"
    type: "Reactor"
  incubators:
    name: "Development Incubators"
    type: "Incubator"
  petri_dishes:
    name: "Testing Petri Dishes"
    type: "Petri Dish"
  laboratories:
    name: "Analysis Laboratories"
    type: "Laboratory"
  factories:
    name: "Production Factories"
    type: "Factory"
